# Configuration file for your GitHub Pages site

# Site settings
title: "Md. Manzurul Islam's Portfolio"
description: "Work as a Python Developer at Bista Solution Inc"
logo : "/assert/img_me.png"

# Theme settings
theme: jekyll-theme-minimal
show_downloads: True
# # Build settings
# markdown: kramdown
# exclude: ["README.md", "Gemfile", "Gemfile.lock", "node_modules", "vendor", "_config.yml"]
